#!/usr/bin/env python3
"""
Standalone EDA script: compute stats from data/train.jsonl and write data/eda_report.md.
Run via: make eda  or  python eda.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TRAIN_PATH = ROOT / "data" / "train.jsonl"
REPORT_PATH = ROOT / "data" / "eda_report.md"


def main() -> None:
    if not TRAIN_PATH.exists():
        print(f"Dataset not found: {TRAIN_PATH}")
        print("Run: make prepare")
        return

    rows: list[tuple[int, int, int]] = []  # idx, input_words, output_words
    with TRAIN_PATH.open() as f:
        for idx, line in enumerate(f):
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except Exception:
                continue
            msgs = obj.get("messages") or []
            user, assistant = "", ""
            for m in msgs:
                if m.get("role") == "user":
                    user = str(m.get("content", ""))
                elif m.get("role") == "assistant":
                    assistant = str(m.get("content", ""))
            in_w = len(user.split())
            out_w = len(assistant.split())
            rows.append((idx, in_w, out_w))

    if not rows:
        print("No valid rows in train.jsonl")
        return

    out_lengths = [r[2] for r in rows]
    n = len(out_lengths)
    total = sum(out_lengths)
    mean = total / n
    sorted_len = sorted(out_lengths)
    median = sorted_len[n // 2] if n % 2 else (sorted_len[n // 2 - 1] + sorted_len[n // 2]) / 2
    p90_idx = int(0.9 * n) if n else 0
    p99_idx = int(0.99 * n) if n else 0
    p90 = sorted_len[min(p90_idx, n - 1)]
    p99 = sorted_len[min(p99_idx, n - 1)]
    min_v = min(out_lengths)
    max_v = max(out_lengths)

    report = f"""# EDA Report — {TRAIN_PATH.name}

- **Total examples:** {n}
- **Output length (words):** min {min_v}, mean {mean:.1f}, median {median:.1f}, p90 {p90}, p99 {p99}, max {max_v}

Generated by `eda.py` (run `make eda`).
"""
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"Wrote {REPORT_PATH}")
    print(f"  Total examples: {n}")
    print(f"  Output length (words): min {min_v}, mean {mean:.1f}, median {median:.1f}, max {max_v}")


if __name__ == "__main__":
    main()
