
# The path to the local model directory or Hugging Face repo.
model: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
# Whether to train (boolean)
train: true

# Directory with {train, valid, test}.jsonl files
data: "./data"

# Type of fine-tuning to perform: lora, dora, or full.
fine_tune_type: full

# The PRNG seed
seed: 0

# Minibatch size.
batch_size: 1

# Iterations to train for.
iters: 1200

# Number of validation batches, -1 uses the entire validation set.
val_batches: 25

# Adam learning rate.
learning_rate: 1e-5

# Number of training steps between loss reporting.
steps_per_report: 10

# Number of training steps between validations.
steps_per_eval: 100

# Save/load path for the fine-tuned weights (Since full FT, this saves the full model weights)
adapter_path: "./models/tinyllama-full-alpaca"

# Save the model every N iterations.
save_every: 200

# Evaluate on the test set after training
test: true

# Number of test set batches, -1 uses the entire test set.
test_batches: 100

# Maximum sequence length.
max_seq_length: 512

# Use gradient checkpointing to reduce memory use.
grad_checkpoint: true
